<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="1" name="chrometest" time="16.539" errors="0" timestamp="2025-02-11T11:36:06 IST">
  <testcase classname="testCases.tc001_AccountRegistrationPage" name="verify_account_regirtration" time="2.921">
    <failure type="java.lang.AssertionError" message="expected [Congratulations! Your new account has been successfully created!] but found [If you already have an account with us, please login at the login page.]">
      <![CDATA[java.lang.AssertionError: expected [Congratulations! Your new account has been successfully created!] but found [If you already have an account with us, please login at the login page.]
at testCases.tc001_AccountRegistrationPage.verify_account_regirtration(tc001_AccountRegistrationPage.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_account_regirtration -->
</testsuite> <!-- chrometest -->
